[tool.poetry]
name = "pytorch-ssd"
version = "0.1.0"
description = ""
authors = ["Hao Gao <qfgaohao@gmail.com>"]
readme = "README.md"
packages = [{ include = "pytorch_ssd", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^2.0"
torch = "2.6.0"
torchvision = "0.21.0"
opencv-python-headless = "^4.8.1.78"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4"
ruff-lsp = "^0.0.53"

[tool.ruff.lint.isort]
known-first-party = ["pytorch_ssd"]

[tool.nix]
format = "poetry-core"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
